# Site settings, note
title: New-Blog
author: Paula Kuku
name: Paula
email: email@domain.com
twitter_username: paulakuku
github_username: PaulinaKukuczka
description: "Great site about Jekyll on GH-Pages. Explore this features."

# Build settings
remote_theme: jekyll/minima
